
export type VisualEffect =
  'FIRE_FLOOR' | 'ICE_MIST' | 'WATER_POOL' | 'FIRE_MIST'
| 'DUST_MIST' | 'SNOW_FLOOR' | 'ICE_STORM' | 'SLUDGE_FLOOR';

export const VISUAL_EFFECTS = {
  FIRE_FLOOR: 0,
  ICE_MIST: 1,
  WATER_POOL: 2,
  FIRE_MIST: 3,
  DUST_MIST: 4,
  SNOW_FLOOR: 5,
  ICE_STORM: 6,
  SLUDGE_FLOOR: 7
};
