
const macroCreatePromise = new Promise((resolve, reject) => {
  exec('npm run task:macros:meta', (e) => {
    if(e) return reject(e);
    resolve();
  });
});

const skilltreeTaskPromise = new Promise((resolve, reject) => {
  exec('npm run task:skilltrees', (e) => {
    if(e) return reject(e);
    resolve();
  });
});

Promise.all([
  macroCreatePromise,
  skilltreeTaskPromise
]).then(() => {
  console.log('Autogenerated files created.');
});
